# Makefile.rules - 手製のメイクファイル
#

# Default target
all: html css

html: $(BUILD_DIR)
	@for i in *.txt; do \
	  TARGET="build/$${i%.txt}.html"; \
	  if [ "$$i" -nt "$$TARGET" ] ; then \
	    echo Processing $$i...; \
	    $(PYTHON) $(RST2HTML) $$i > "$$TARGET"; \
	  fi; \
	done

css: $(CSSFILE) $(BUILD_DIR)
	@cp -u $(CSSFILE) $(BUILD_DIR)

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

clean:
	find $(BUILD_DIR) -name note.css -delete
	find $(BUILD_DIR) -name '*.html' -delete
