# Makefile.rules - 手製のメイクファイル
#

# Default target
all: html css

html: $(TARGET_HTML_FILES)

$(TARGET_HTML_FILES): $(BUILD_DIR)

$(BUILD_DIR)/%.html: %.txt
	@echo Processing $< ... 
	@$(PYTHON) $(RST2HTML) $< > $@

css: $(CSSFILE) $(BUILD_DIR)
	@cp -u $(CSSFILE) $(BUILD_DIR)

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

clean:
	find $(BUILD_DIR) -name note.css -delete
	find $(BUILD_DIR) -name '*.html' -delete

test: all
	$(BROWSER) $(BUILD_DIR)/index.html
