# Makefile.vars - 各種定数の定義
#

# make を実行するディレクトリ
SOURCE_DIR=.

# ビルドしたファイルを格納するディレクトリ
BUILD_DIR=$(SOURCE_DIR)/build

# CSS ファイル名
CSSFILE=$(SOURCE_DIR)/note.css

# Python インタープリター本体
PYTHON=D:/Python26/python.exe

# docutil のスクリプトのパス
RST2HTML=D:/Python26/Scripts/rst2html.py

# シェル
SHELL=/bin/bash
