classDiagram
    direction TB
        SettingsSpec <|-- OptionParser
        SettingsSpec <|-- Component

    class SettingsSpec{
        +tuple settings_spec$
        +dict settings_defaults$
        +dict settings_default_overrides$
        +tuple relative_path_settings$
        +str config_section$
        +tuple config_section_dependencies$
    }

    class OptionParser{
        +tuple settings_spec$
        +dict settings_defaults$
        +tuple relative_path_settings$
        +str config_section$
    }

    class Component{
        +str component_type$
        #tuple supported$
        +supports(str) bool
    }
