classDiagram
    direction TB
        TransformSpec <|-- Component
        TransformSpec <|-- Transformer
        TransformSpec <|-- Input
        TransformSpec <|-- Output

    class TransformSpec{
        +get_transforms()
    }
