classDiagram
    direction TB
        SettingsSpec <|-- Component
        TransformSpec <|-- Component

    class SettingsSpec{
        +tuple settings_spec$
        +dict settings_defaults$
        +dict settings_default_overrides$
        +tuple relative_path_settings$
        +str config_section$
        +tuple config_section_dependencies$
    }

    class TransformSpec{
        +get_transforms()
    }

    class Component{
        +str component_type$
        #tuple supported$
        +supports(str) bool
    }
