' 
@startuml

skinparam monochrome true

'object publisher
'object document
'object reader
'object parser
'object writer
'object source
'object destination
'object settings

publisher -- document
publisher -left- reader
publisher -- parser
publisher -right- writer
publisher -- source
publisher -- destination
publisher -up- settings

reader -- parser
reader -- document
reader -- settings
reader -- source

parser -- document

writer -- destination
writer -- document

document -- settings

hide circle
hide members

@enduml
