' docutils-publisher-sd.pu
@startuml

hide footbox
skinparam monochrome true

participant ":Publisher" as Publisher

[-> Publisher : publish
activate Publisher

' self.process_command_line
Publisher -> Publisher: process_command_line(argv, ...)
activate Publisher
deactivate Publisher

' self.set_io
Publisher -> Publisher: set_io
activate Publisher
create "source:Input" as Input
Publisher -> Input : <<create>>
create "destination:Output" as Output
Publisher -> Output : <<create>>
deactivate Publisher

' self.reader.read
Publisher -> ":Reader" as Reader : read(source, parser, settings)
activate Reader
Reader --> Publisher : document
deactivate Reader

' self.apply_transform
Publisher -> Publisher: apply_transform
activate Publisher
deactivate Publisher

' self.writer.write
Publisher -> ":Writer" as Writer : write(document, destination)
activate Writer
Writer --> Publisher : output
deactivate Writer

' self.writer.assemble_parts
Publisher -> Writer: assemble_parts
activate Writer
Writer --> Publisher
deactivate Writer

[<- Publisher : output
deactivate Publisher

@enduml
