flowchart BT
    glvalue & rvalue --> expression
    lvalue --> glvalue
    xvalue --> glvalue & rvalue
    prvalue --> rvalue

    linkStyle 0,1,2,3,4,5 stroke:#000,stroke-width:1px,fill:none;
    classDef default fill:none,stroke:none;
