---
title: Node shapes
---
flowchart LR
    nodeA(A node with round edges)
    nodeB([A stadium-shaped node])
    nodeC[[A node in a subroutine shape]]
    nodeD[(A node in a cylindrical shape)]
    nodeE((A node in the form of a circle))
    nodeF>A node in an asymmetric shape]
    nodeG{A node rhombus}
    nodeH{{A hexagon node}}
    nodeI[/Parallelogram/]
    nodeJ[\Parallelogram alt\]
    nodeK[/Trapezoid\]
    nodeL[\Trapezoid alt/]
